### ISSUE TITLE
Supervisión métricas y logs con Grafana

### ISSUE THREAD

**Issue by gonzaleztroyano** [gonzaleztroyano/ASIR2-IAW-SCRIPT#18]
Instalar el agente Grafana Cloud para Prometheus y Loki. 

Ejemplo de configuración:
```
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*log
      - job_name: apachelogs
        static_configs:
          - targets: [localhost]
            labels:
              job: apachelogs
              __path__: /var/log/apache2/*log
``` 

**Importante**: designar jobnames distintos para cada sitio. Exclusivos, para facilitar la búsqueda. ¿Esto dará problemas? ¿Uso de labels?

**Synthetic Monitoring**
¿Cómo supervisar sin cargar el servidor?
